"""empty message

Revision ID: 74824bed1269
Revises: 
Create Date: 2023-01-16 10:48:32.719546

"""
import sqlalchemy as sa
from alembic import op
from sqlalchemy import orm

from src.domain.renewal_type.models import TypeName
from src.infrastructure.database.models import RenewalType

# revision identifiers, used by Alembic.
revision = "74824bed1269"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "renewal_type",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "user",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("telegram_id", sa.BigInteger(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column(
            "created_time",
            sa.DateTime(),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.Column("inviter_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["inviter_id"],
            ["user.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "subscription_renewal",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column(
            "created_time",
            sa.DateTime(),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.Column("days", sa.Integer(), nullable=False),
        sa.Column("renewal_type_id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["renewal_type_id"],
            ["renewal_type.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["user.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###
    bind = op.get_bind()
    session = orm.Session(bind)

    payment = RenewalType(id=1, name=TypeName.payment)
    refferal = RenewalType(id=2, name=TypeName.referral)
    free_trial = RenewalType(id=3, name=TypeName.free_trial)

    session.add_all(
        (
            payment,
            refferal,
            free_trial,
        ),
    )

    session.commit()


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("subscription_renewal")
    op.drop_table("user")
    op.drop_table("renewal_type")
    # ### end Alembic commands ###
